require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'config/environments/*.rb'
    - 'db/schema.rb'

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
