services:
  application:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: idyie-web-application
    env_file: .env
    networks:
      - idyie-network
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: idyie-web-mariadb
    env_file: .env
    networks:
      - idyie-network
    ports:
      - "3308:3306"
    volumes:
      - idyie-web-mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  idyie-network:
    external: true

volumes:
  idyie-web-mariadb:
