services:
  application:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: idyie-web-application
    environment:
      IDYIE_API_URL: $IDYIE_API_URL
      PORT: $PORT
    networks:
      - idyie-network
    ports:
      - "$PORT:$PORT"
    stdin_open: true
    tty: true
    volumes:
      - .:/app

  mariadb:
    image: mariadb:11.2.3
    container_name: idyie-web-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    networks:
      - idyie-network
    volumes:
      - idyie-web-mariadb:/var/lib/mysql

networks:
  default:
    driver: bridge
  idyie-network:
    external: true
    name: idyie-network

volumes:
  idyie-web-mariadb: