name: Lint, Build, and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with RuboCop
    runs-on: ubuntu-latest
    container:
      image: ruby:3.2.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update -qy
          apt-get install -y nodejs
          gem install bundler
          bundle install --jobs $(nproc) --retry 3

      - name: Run RuboCop
        run: bundle exec rubocop

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: lint
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose build
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          PORT: ${{ secrets.PORT }}

  test:
    name: Run RSpec tests
    runs-on: ubuntu-latest
    needs: build
    env:
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      PORT: ${{ secrets.PORT }}
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Docker network
        run: docker network create idyie-network || true

      - name: Setup Docker Compose
        run: docker compose up -d

      - name: Wait for MariaDB
        run: docker compose exec mariadb mariadb-admin --silent --wait=30 -uroot -ppassword ping || exit 1

      - name: Run DB Migrations
        run: docker compose exec application rails db:create db:migrate

      - name: Run RSpec
        run: docker compose exec application bundle exec rspec
